id: A416C66A6
title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:20:15.208860
  last_modified_at: 2022-02-28 23:20:15.208868
