id: A416C66A6
title: Prayer for the Swift Rebirth of the Fourth Dodrupchen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:20:15.220427
  last_modified_at: 2022-02-28 23:20:15.220434
