id: A416C66A6
title: Guru Yoga
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:20:15.211952
  last_modified_at: 2022-02-28 23:20:15.211954
