id: A416C66A6
title: Prayer for the Long Life Dodrupchen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:20:15.218515
  last_modified_at: 2022-02-28 23:20:15.218519
