id: A416C66A6
title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé Palzangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:20:15.213695
  last_modified_at: 2022-02-28 23:20:15.213699
